name = "LongwaveModePropagator"
uuid = "38c6559a-e0a7-48c6-827d-3f02e2d19cec"
authors = ["Forrest Gasdia <EP-Guy@users.noreply.github.com>"]
version = "0.3.5"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModifiedHankelFunctionsOfOrderOneThird = "b1c65800-dbf0-11e8-0001-4d87e1e07e69"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Romberg = "ff01fdde-158c-414c-948f-c94b4a236685"
RootsAndPoles = "a0859a10-ccb4-11e8-145d-674b3750773a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
DiffEqCallbacks = "2"
FunctionWrappers = "1.1"
Interpolations = "0.14.4"
JSON3 = "1"
ModifiedHankelFunctionsOfOrderOneThird = "1"
OrdinaryDiffEq = "5,6"
Parameters = "0.12"
PolynomialRoots = "1"
ProgressLogging = "0.1.3"
Romberg = "0.2"
RootsAndPoles = "1,2"
StaticArrays = "0.12,1"
StructTypes = "1"
julia = "1.5"
