[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FaradayInternationalReferenceIonosphere = "13f5a3bc-1e41-4c76-a7e5-29a214aba9ea"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NormalHermiteSplines = "67f7b941-d455-546b-99f0-07b665bf0aaf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RootsAndPoles = "a0859a10-ccb4-11e8-145d-674b3750773a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
CSV = "0.10"
Distances = "0.10"
Documenter = "1"
FaradayInternationalReferenceIonosphere = "0.2"
HDF5 = "0.16 - 0.17"
Interpolations = "0.14.4,0.15"
JSON3 = "1"
Literate = "2"
NormalHermiteSplines = "0.5"
Plots = "1"
ProgressMeter = "1"
RootsAndPoles = "2"
TimerOutputs = "0.5"
julia = "1.10"
